language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
before-install:
  - "test $TRAVIS_NODE_VERSION == '5' || npm i -g npm"

script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "AxhJbpY7MxAMtQBzREvUqhLQ5k9kC/zID8DFRg2OW1FuKfutUZsXML5ruhN94kqxMiUZgMwfAVt338QA7D3ekSOU8tNloQ/7gW8eWfVgX7vkHjPPZSQP29WZlgkQn41Qqtt3+w3kBsxe581JUMKKZlRrYinC1QQMkArhxMxxGjk3t4Fcj52mVuyqosnyi0YNwQoOb0p4qCn3uOi9gOAGGjQBuYMEBY8sdyY9XFQe1Qzr8msIa5g8JXCt+w82TYKytxDxcxmg3muJ4NjwjDHxbdEB0Xw3Nun7prbfKBOzVkgWH5kIgHqjEurPdFxWEbhR74n/hIBDpvpqEE4/oEwMeXgJ/SgKKwMxDibhA4YHnTuLCpJBxkArSB3VJvD08FG9pU/i736YzAkiePNfTsLRfpGZtSQWkNpr6rHINI+pdMpoHSmOaSxChiQTSkq/isv5410bmgWracn1Ba0AwKjsfUKcRtLzerWpeFe+f4tTfGRhZoMrt/h4luyplg1suFprW3U/c8nPa52OaF6chFE8fP8jXz3WM8tmtiURTZrOsaLjlu9aBvQhRBy/Cbet//4DQaEz7NK3CTdlyjgngF6ysb6bmmY0HESELitN164Oe8wseObGl0xM/+3WhPXuEWIvWdqiBcyjroztpVGwFBK/0XOVlm2K4sDt3eSlA4BLwLc="
